# keys: /usr/include/linux/input-event-codes.h

swipe:
  3:
    begin:
      command: 'ydotool key 56:1'
    right:
      update:
        command: 'ydotool key 15:1 15:0'
        interval: 1
    left:
      update:
        command: 'ydotool key 15:1 42:1 15:0 42:0'
        interval: 1
    end:
      command: 'ydotool key 56:0'
